In [80]:
import pandas as pd
import numpy as np

In [81]:
data = pd.read_csv('FashionDataset.csv')

In [82]:
data.head()

,Unnamed: 0,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women

In [83]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 30758 entries, 0 to 30757
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  30758 non-null  int64
 1   BrandName   30758 non-null  str
 2   Deatils     30758 non-null  str
 3   Sizes       30758 non-null  str
 4   MRP         30758 non-null  str
 5   SellPrice   30758 non-null  str
 6   Discount    30758 non-null  str
 7   Category    30758 non-null  str
dtypes: int64(1), str(7)
memory usage: 1.9 MB

In [84]:
data.shape

(30758, 8)

In [85]:
data.columns

Index(['Unnamed: 0', 'BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice',
       'Discount', 'Category'],
      dtype='str')

In [86]:
data.drop(columns = 'Unnamed: 0', inplace = True)

In [87]:
data

,BrandName,Deatils,Sizes,MRP,SellPrice,Discount,Category
0,life,solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,only,polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,fratini,solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,zink london,stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,life,regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
30753,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
30754,Nan,Nan,Nan,Nan,Nan,Nan,Jewellery-Women
30755,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
30756,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
30757,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [88]:
data.columns

Index(['BrandName', 'Deatils', 'Sizes', 'MRP', 'SellPrice', 'Discount',
       'Category'],
      dtype='str')

In [89]:
data.rename(columns = {'Deatils':'Details'},inplace = True)

In [90]:
data.duplicated().sum()

np.int64(2827)

In [91]:
data.drop_duplicates(inplace = True)

In [92]:
data.duplicated().sum()

np.int64(0)

In [93]:
data = data.reset_index().drop(columns ='index')

In [94]:
data.tail()

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
27926,shaya by caratlane,the wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
27927,swarovski,crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
27928,jewelz,ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
27929,estelle,womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
27930,estelle,womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [95]:
data.isna().sum().sum()

np.int64(0)

In [96]:
data.dropna(inplace = True)

In [97]:
data['BrandName'] = data['BrandName'].apply(lambda x : x.capitalize())

In [98]:
data['Details'] = data['Details'].apply(lambda x : x.capitalize())

In [99]:
data

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
27926,Shaya by caratlane,The wing woman clover charm necklace,Nan,Nan,1250,Nan,Jewellery-Women
27927,Swarovski,Crystal stylish womens rodhium earrings,Nan,Nan,8950,Nan,Jewellery-Women
27928,Jewelz,Ethnic gold plated jhumki earrings,Nan,Rs\n1839,643,65% off,Jewellery-Women
27929,Estelle,Womens gold plated double line fancy white and...,Nan,Nan,2799,Nan,Jewellery-Women
27930,Estelle,Womens gold plated bridge designer mangalsutra...,Nan,Nan,1899,Nan,Jewellery-Women

In [100]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 27931 entries, 0 to 27930
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BrandName  27931 non-null  str
 1   Details    27931 non-null  str
 2   Sizes      27931 non-null  str
 3   MRP        27931 non-null  str
 4   SellPrice  27931 non-null  str
 5   Discount   27931 non-null  str
 6   Category   27931 non-null  str
dtypes: str(7)
memory usage: 1.5 MB

In [101]:
type(data['Sizes'][27929])

str

In [102]:
data['Sizes'] = data['Sizes'].replace('Nan','NA VALUED')

In [103]:
data['Sizes'].tail(20)

27911    NA VALUED
27912    NA VALUED
27913    NA VALUED
27914    NA VALUED
27915    NA VALUED
27916    NA VALUED
27917    NA VALUED
27918    NA VALUED
27919    NA VALUED
27920    NA VALUED
27921    NA VALUED
27922    NA VALUED
27923    NA VALUED
27924    NA VALUED
27925    NA VALUED
27926    NA VALUED
27927    NA VALUED
27928    NA VALUED
27929    NA VALUED
27930    NA VALUED
Name: Sizes, dtype: str

In [104]:
data = data[data['Sizes'] != 'NA VALUED']

In [105]:
data['Discount'] = data['Discount'].replace('Nan','No Discount')

In [106]:
data['Discount'].tail(50)

24099        10% off
24100    No Discount
24101    No Discount
24102    No Discount
24103    No Discount
24104        50% off
24105    No Discount
24106    No Discount
24107        30% off
24108    No Discount
24109        20% off
24110        30% off
24111    No Discount
24112    No Discount
24113        30% off
24114    No Discount
24115    No Discount
24116        50% off
24117    No Discount
24118        50% off
24119        50% off
24120        58% off
24121        50% off
24122    No Discount
24123        50% off
24124    No Discount
24125    No Discount
24126    No Discount
24127    No Discount
24128        30% off
24129    No Discount
24130    No Discount
24131    No Discount
24132    No Discount
24133        30% off
24134    No Discount
24135        30% off
24136    No Discount
24137    No Discount
24138        35% off
24139    No Discount
24140    No Discount
24141        50% off
24142        50% off
24143    No Discount
24344        70% off
24731        33% off
25791        33% off
26028    No Discount
26078    No Discount
Name: Discount, dtype: str

In [107]:
data['MRP'] = data['MRP'].replace('Nan','No Value')

In [108]:
data = data.reset_index().drop(columns = 'index')

In [109]:
data

,BrandName,Details,Sizes,MRP,SellPrice,Discount,Category
0,Life,Solid cotton blend collar neck womens a-line d...,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1699,849,50% off,Westernwear-Women
1,Only,Polyester peter pan collar womens blouson dres...,"Size:34,36,38,40",Rs\n3499,2449,30% off,Westernwear-Women
2,Fratini,Solid polyester blend wide neck womens regular...,"Size:Large,X-Large,XX-Large",Rs\n1199,599,50% off,Westernwear-Women
3,Zink london,Stripes polyester sweetheart neck womens dress...,"Size:Large,Medium,Small,X-Large",Rs\n2299,1379,40% off,Westernwear-Women
4,Life,Regular fit regular length denim womens jeans ...,"Size:26,28,30,32,34,36",Rs\n1699,849,50% off,Westernwear-Women
...,...,...,...,...,...,...,...
22682,Swiss eagle,Womens analogue metallic watch,Size:Error Size,Rs\n13990,4197,70% off,Watches-Women
22683,Lawman watches,Womens rose gold dial stainless steel analogue...,Size:Error Size,Rs\n7499,4999,33% off,Watches-Women
22684,Lawman watches,Womens silver dial stainless steel analogue wa...,Size:Error Size,Rs\n5999,3999,33% off,Watches-Women
22685,Miu miu,Eau de parfum - 50 ml,Size:Error Size,No Value,6100,No Discount,Fragrance-Women
22686,Miu miu,Eau de parfum - 30 ml,Size:Error Size,No Value,4400,No Discount,Fragrance-Women

In [110]:
data.to_csv('cleaned_fashion.csv', index = False)